/**
 * Parse the model's fenced recommendation block.
 *
 * ── PARSING POSTURE ───────────────────────────────────────────────────────────────────
 * This parser is deliberately LENIENT about shape and STRICT about vocabulary.
 *
 * Lenient about shape, because the block is generated by a language model mid-stream: a
 * missing field, a stray trailing comma, or no block at all are all normal. None of them
 * should surface as an error, because the prose answer is independently useful — losing a
 * good assessment because its JSON tail was malformed would be the worst possible trade.
 *
 * Strict about vocabulary, because `action_type` is CHECK-constrained in Postgres and M2
 * will switch on it. An unrecognised action is coerced to `other` and the original string
 * is preserved in `raw.action_type_raw`, so nothing is lost and the insert cannot fail.
 *
 * The one thing this module must never do is invent a value. A field the model did not
 * supply stays null.
 */

import { ACTION_TYPES, RECOMMENDATION_FENCE, type ActionType } from './prompt.js';

export interface ParsedRecommendation {
  action_type: ActionType;
  target_label: string;
  target_corridor: string | null;
  target_direction: string | null;
  expected_effect: string;
  effect_direction: 'decrease' | 'increase' | 'unclear' | null;
  magnitude: number | null;
  magnitude_unit: string | null;
  confidence: 'low' | 'medium' | 'high' | null;
  rationale: string | null;
  raw: Record<string, unknown>;
}

export interface ParsedResponse {
  /** The response with the fenced block removed — what the UI renders as prose. */
  prose: string;
  recommendations: ParsedRecommendation[];
  /** True when a fence was present but its contents could not be parsed as JSON. */
  malformed: boolean;
}

const EFFECT_DIRECTIONS = new Set(['decrease', 'increase', 'unclear']);
const CONFIDENCES = new Set(['low', 'medium', 'high']);
const DIRECTIONS = new Set(['N', 'S', 'E', 'W']);

/**
 * Match the fenced block.
 *
 * Tolerates: the language tag on the same line as the opening fence, extra whitespace, and
 * an UNCLOSED fence — the last case matters because a stream truncated by the token limit
 * or the 120s proxy ceiling leaves the block open, and we would rather recover the
 * recommendations that did arrive than drop all of them.
 */
function extractFence(text: string): { json: string; start: number; end: number } | null {
  const open = new RegExp('```[ \\t]*' + RECOMMENDATION_FENCE + '[ \\t]*\\r?\\n', 'i');
  const m = open.exec(text);
  if (!m) return null;

  const bodyStart = m.index + m[0].length;
  const close = text.indexOf('```', bodyStart);
  const bodyEnd = close === -1 ? text.length : close;

  return {
    json: text.slice(bodyStart, bodyEnd),
    start: m.index,
    end: close === -1 ? text.length : close + 3,
  };
}

/**
 * Best-effort JSON recovery.
 *
 * Tries strict parse first. If that fails, applies two repairs that cover the failure modes
 * actually seen from streamed LLM output: a trailing comma before a closing bracket, and a
 * truncated array (stream cut mid-object) — for which we salvage the complete prefix by
 * trimming back to the last balanced `}` and closing the array.
 */
function parseJsonLenient(src: string): unknown {
  const text = src.trim();
  if (!text) return null;

  try {
    return JSON.parse(text);
  } catch {
    // fall through to repairs
  }

  const noTrailingCommas = text.replace(/,(\s*[}\]])/g, '$1');
  try {
    return JSON.parse(noTrailingCommas);
  } catch {
    // fall through
  }

  // Truncated array: keep everything up to the last closing brace, then close the array.
  const lastBrace = noTrailingCommas.lastIndexOf('}');
  if (noTrailingCommas.trimStart().startsWith('[') && lastBrace !== -1) {
    const salvaged = noTrailingCommas.slice(0, lastBrace + 1).replace(/,\s*$/, '') + ']';
    try {
      return JSON.parse(salvaged);
    } catch {
      // give up
    }
  }
  return null;
}

function str(v: unknown): string | null {
  if (typeof v === 'string') {
    const t = v.trim();
    return t === '' || t.toLowerCase() === 'null' ? null : t;
  }
  if (typeof v === 'number' && Number.isFinite(v)) return String(v);
  return null;
}

function normaliseActionType(v: unknown): { type: ActionType; matched: boolean } {
  const s = str(v);
  if (!s) return { type: 'other', matched: false };
  // Accept the canonical snake_case form, plus loose spellings ("Ramp Metering", "ramp-metering").
  const key = s.toLowerCase().replace(/[\s-]+/g, '_');
  const hit = (ACTION_TYPES as readonly string[]).includes(key);
  return hit ? { type: key as ActionType, matched: true } : { type: 'other', matched: false };
}

/**
 * Pull a direction out of a target label like "I-405 S" or "US-101 southbound".
 * Only used when the model did not supply `direction` explicitly.
 */
function inferDirection(label: string | null): string | null {
  if (!label) return null;
  const compass = /\b([NSEW])B?\b/.exec(label.toUpperCase());
  if (compass && DIRECTIONS.has(compass[1])) return compass[1];
  const word = /\b(north|south|east|west)bound\b/i.exec(label);
  if (word) return word[1][0].toUpperCase();
  return null;
}

/** Pull a corridor label like "I-405" / "US-101" / "SR-99" out of a target string. */
function inferCorridor(label: string | null): string | null {
  if (!label) return null;
  const m = /\b((?:I|US|SR|CA)-\d+)\b/i.exec(label);
  return m ? m[1].toUpperCase() : null;
}

function normaliseOne(input: unknown): ParsedRecommendation | null {
  if (!input || typeof input !== 'object' || Array.isArray(input)) return null;
  const o = input as Record<string, unknown>;

  const targetLabel = str(o.target) ?? str(o.target_label) ?? str(o.corridor);
  const expected = str(o.expected_effect) ?? str(o.effect) ?? str(o.expected);

  // A recommendation with neither a target nor an effect carries no information — drop it
  // rather than persisting a row of nulls.
  if (!targetLabel && !expected) return null;

  const { type, matched } = normaliseActionType(o.action_type ?? o.action);

  const effectDirRaw = str(o.effect_direction)?.toLowerCase() ?? null;
  const confidenceRaw = str(o.confidence)?.toLowerCase() ?? null;

  const magnitudeRaw = o.magnitude;
  const magnitude =
    typeof magnitudeRaw === 'number' && Number.isFinite(magnitudeRaw)
      ? magnitudeRaw
      : typeof magnitudeRaw === 'string' && magnitudeRaw.trim() !== '' && !isNaN(Number(magnitudeRaw))
        ? Number(magnitudeRaw)
        : null;

  const explicitDirection = str(o.direction)?.toUpperCase() ?? null;
  const direction =
    explicitDirection && DIRECTIONS.has(explicitDirection)
      ? explicitDirection
      : inferDirection(targetLabel);

  return {
    action_type: type,
    target_label: targetLabel ?? 'unspecified',
    target_corridor: str(o.corridor)?.toUpperCase() ?? inferCorridor(targetLabel),
    target_direction: direction,
    expected_effect: expected ?? 'unspecified',
    effect_direction:
      effectDirRaw && EFFECT_DIRECTIONS.has(effectDirRaw)
        ? (effectDirRaw as ParsedRecommendation['effect_direction'])
        : null,
    magnitude,
    magnitude_unit: str(o.magnitude_unit),
    confidence:
      confidenceRaw && CONFIDENCES.has(confidenceRaw)
        ? (confidenceRaw as ParsedRecommendation['confidence'])
        : null,
    rationale: str(o.rationale),
    // Keep the verbatim object, plus the unmatched action string when we coerced to `other`,
    // so a vocabulary change can be replayed against what the model actually said.
    raw: matched ? o : { ...o, action_type_raw: str(o.action_type ?? o.action) },
  };
}

/**
 * Split a model response into prose + structured recommendations.
 *
 * Never throws. A response with no fence yields `{ prose: <whole text>, recommendations: [] }`.
 */
export function parseModelResponse(text: string): ParsedResponse {
  if (!text) return { prose: '', recommendations: [], malformed: false };

  const fence = extractFence(text);
  if (!fence) return { prose: text.trim(), recommendations: [], malformed: false };

  const prose = (text.slice(0, fence.start) + text.slice(fence.end)).trim();
  const parsed = parseJsonLenient(fence.json);

  if (parsed === null) {
    // Fence present but unusable. Surface the prose; flag it so the caller can log.
    return { prose, recommendations: [], malformed: true };
  }

  const arr = Array.isArray(parsed) ? parsed : [parsed];
  const recommendations = arr
    .map(normaliseOne)
    .filter((r): r is ParsedRecommendation => r !== null)
    .slice(0, 5); // matches the prompt's stated cap

  return { prose, recommendations, malformed: false };
}

/**
 * Strip an in-progress fence from a partial stream, for live rendering.
 *
 * While streaming, the raw JSON tail would otherwise flash on screen before the block
 * closes. The client renders `visibleProse` and the structured cards appear once the turn
 * completes.
 */
export function stripPartialFence(text: string): string {
  const idx = text.search(new RegExp('```[ \\t]*' + RECOMMENDATION_FENCE, 'i'));
  return idx === -1 ? text : text.slice(0, idx).trimEnd();
}
