// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    available_days: {
        name: "available_days";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          day: string;
          /** @sqlType INT */
          day_of_week: number;
          /** @sqlType INT */
          is_weekend: number;
          /** @sqlType STRING */
          day_name: string;
          /** @sqlType INT */
          station_count: number;
        }>;
      };
    corridor_options: {
        name: "corridor_options";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          freeway: string;
          /** @sqlType INT */
          station_count: number;
        }>;
      };
    h3_congestion_hexes: {
        name: "h3_congestion_hexes";
        parameters: {
          /** DATE - use sql.date() */
          day: SQLDateMarker;
          /** STRING - use sql.string() */
          freeway: SQLStringMarker;
          /** INT - use sql.int() */
          from_bucket: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType INT */
          hex_count: number;
          /** @sqlType INT */
          first_bucket: number;
          /** @sqlType INT */
          max_congestion_pct: number;
          /** @sqlType STRING */
          hex_ids: string;
          /** @sqlType STRING */
          congestion_pct: string;
          /** @sqlType STRING */
          speed_half: string;
        }>;
      };
    station_geometry: {
        name: "station_geometry";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          station_id: string;
          /** @sqlType STRING */
          freeway: string;
          /** @sqlType STRING */
          direction: string;
          /** @sqlType INT */
          district: number;
          /** @sqlType STRING */
          county: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType DOUBLE */
          postmile: number;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType INT */
          num_lanes: number;
          /** @sqlType STRING */
          station_type: string;
          /** @sqlType STRING */
          h3_r7: string;
          /** @sqlType STRING */
          h3_r8: string;
          /** @sqlType DOUBLE */
          baseline_capacity_vph: number;
          /** @sqlType INT */
          baseline_lanes: number;
        }>;
      };
    traffic_time_matrix: {
        name: "traffic_time_matrix";
        parameters: {
          /** DATE - use sql.date() */
          day: SQLDateMarker;
          /** STRING - use sql.string() */
          freeway: SQLStringMarker;
          /** INT - use sql.int() */
          from_bucket: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType INT */
          n: number;
          /** @sqlType INT */
          first_bucket: number;
          /** @sqlType INT */
          last_bucket: number;
          /** @sqlType INT */
          stations: number;
          /** @sqlType STRING */
          flow: string;
          /** @sqlType STRING */
          speed_half: string;
          /** @sqlType STRING */
          vc_pct: string;
          /** @sqlType STRING */
          incident: string;
        }>;
      };
  }
}
